
import java.io.IOException;
import java.io.RandomAccessFile;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CEIA_____
 */
public class simuladorVendas extends javax.swing.JFrame {

    /**
     * Creates new form simuladorVendas
     */
    String pedido = "";
    int r=0;
    public simuladorVendas() {
        initComponents();
    }
    //double total, subtotal=0, troco, adicionais=0, dinheiro;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jrb_burguerbacon = new javax.swing.JRadioButton();
        jrb_burguerfrango = new javax.swing.JRadioButton();
        jrb_modadacasa = new javax.swing.JRadioButton();
        jrb_burguerduplo = new javax.swing.JRadioButton();
        jl_toleburguer = new javax.swing.JLabel();
        jl_precoburguerbacon = new javax.swing.JLabel();
        jl_precoburguerfrango = new javax.swing.JLabel();
        jl_precoburguermodadacasa = new javax.swing.JLabel();
        jl_precoburguerduplo = new javax.swing.JLabel();
        jl_adicionais = new javax.swing.JLabel();
        jl_burguers = new javax.swing.JLabel();
        jl_R$ = new javax.swing.JLabel();
        jl_R$2 = new javax.swing.JLabel();
        jl_R$3 = new javax.swing.JLabel();
        jl_R$4 = new javax.swing.JLabel();
        jcb_queijo = new javax.swing.JCheckBox();
        jcb_catupiry = new javax.swing.JCheckBox();
        jcb_cheddar = new javax.swing.JCheckBox();
        jcb_barbecue = new javax.swing.JCheckBox();
        jl_bebidas = new javax.swing.JLabel();
        jl_R$5 = new javax.swing.JLabel();
        jl_R$6 = new javax.swing.JLabel();
        jl_R$7 = new javax.swing.JLabel();
        jl_R$8 = new javax.swing.JLabel();
        jl_R$9 = new javax.swing.JLabel();
        jl_R$10 = new javax.swing.JLabel();
        jl_R$11 = new javax.swing.JLabel();
        jl_precoqueijo = new javax.swing.JLabel();
        jl_precocatupiry = new javax.swing.JLabel();
        jl_precocheddar = new javax.swing.JLabel();
        jl_precobarbecue = new javax.swing.JLabel();
        jl_precoagua = new javax.swing.JLabel();
        jl_precorefrigerante = new javax.swing.JLabel();
        jl_precocerveja = new javax.swing.JLabel();
        jrb_agua = new javax.swing.JRadioButton();
        jrb_refri = new javax.swing.JRadioButton();
        jrb_cerveja = new javax.swing.JRadioButton();
        jb_calcular = new javax.swing.JButton();
        jb_resetar = new javax.swing.JButton();
        jl_subtotal = new javax.swing.JLabel();
        jl_total = new javax.swing.JLabel();
        jl_totaladicionais = new javax.swing.JLabel();
        jl_entregarapida = new javax.swing.JLabel();
        jl_whats = new javax.swing.JLabel();
        jtf_subtotal = new javax.swing.JTextField();
        jtf_adicionais = new javax.swing.JTextField();
        jtf_total = new javax.swing.JTextField();
        jl_dinheiro = new javax.swing.JLabel();
        jl_nome = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jl_rua = new javax.swing.JLabel();
        btn_gerarpedido = new javax.swing.JButton();
        jtf_rua = new javax.swing.JTextField();
        jl_numero = new javax.swing.JLabel();
        jtf_numero = new javax.swing.JTextField();
        jtf_bairro = new javax.swing.JTextField();
        jl_bairro = new javax.swing.JLabel();
        jtf_cep = new javax.swing.JTextField();
        jl_cep = new javax.swing.JLabel();
        jtf_celular = new javax.swing.JTextField();
        jl_celular = new javax.swing.JLabel();
        jb_fundo = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CEIA_____\\Desktop\\burguer cortado novo.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\CEIA_____\\Desktop\\burguer cortado novo.png")); // NOI18N
        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 750));
        setMinimumSize(new java.awt.Dimension(400, 750));
        setPreferredSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        jrb_burguerbacon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_burguerbacon.setForeground(new java.awt.Color(255, 255, 255));
        jrb_burguerbacon.setText("Burguer Bacon......................");
        jrb_burguerbacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_burguerbaconActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_burguerbacon);
        jrb_burguerbacon.setBounds(20, 180, 170, 24);

        jrb_burguerfrango.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_burguerfrango.setForeground(new java.awt.Color(255, 255, 255));
        jrb_burguerfrango.setText("Burguer Frango..........................");
        jrb_burguerfrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_burguerfrangoActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_burguerfrango);
        jrb_burguerfrango.setBounds(20, 220, 170, 24);

        jrb_modadacasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_modadacasa.setForeground(new java.awt.Color(255, 255, 255));
        jrb_modadacasa.setText("Burguer moda da casa....");
        jrb_modadacasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_modadacasaActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_modadacasa);
        jrb_modadacasa.setBounds(20, 270, 180, 24);

        jrb_burguerduplo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_burguerduplo.setForeground(new java.awt.Color(255, 255, 255));
        jrb_burguerduplo.setText("Burguer duplo...................");
        jrb_burguerduplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_burguerduploActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_burguerduplo);
        jrb_burguerduplo.setBounds(20, 320, 170, 24);

        jl_toleburguer.setFont(new java.awt.Font("Bernard MT Condensed", 0, 55)); // NOI18N
        jl_toleburguer.setForeground(new java.awt.Color(255, 255, 255));
        jl_toleburguer.setText("TOLEBURGUER");
        getContentPane().add(jl_toleburguer);
        jl_toleburguer.setBounds(120, 20, 320, 70);

        jl_precoburguerbacon.setText(" 21,90");
        getContentPane().add(jl_precoburguerbacon);
        jl_precoburguerbacon.setBounds(190, 190, 60, 20);

        jl_precoburguerfrango.setText("18,90");
        getContentPane().add(jl_precoburguerfrango);
        jl_precoburguerfrango.setBounds(190, 280, 40, 20);

        jl_precoburguermodadacasa.setText("21,90");
        getContentPane().add(jl_precoburguermodadacasa);
        jl_precoburguermodadacasa.setBounds(190, 240, 40, 20);

        jl_precoburguerduplo.setText("24,90");
        getContentPane().add(jl_precoburguerduplo);
        jl_precoburguerduplo.setBounds(190, 330, 40, 20);

        jl_adicionais.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        jl_adicionais.setForeground(new java.awt.Color(255, 255, 255));
        jl_adicionais.setText("ADICIONAIS");
        jl_adicionais.setToolTipText("");
        getContentPane().add(jl_adicionais);
        jl_adicionais.setBounds(270, 140, 150, 40);

        jl_burguers.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        jl_burguers.setForeground(new java.awt.Color(255, 255, 255));
        jl_burguers.setText("BURGUERS");
        jl_burguers.setToolTipText("");
        jl_burguers.setAutoscrolls(true);
        getContentPane().add(jl_burguers);
        jl_burguers.setBounds(70, 140, 180, 30);

        jl_R$.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$.setText("R$");
        getContentPane().add(jl_R$);
        jl_R$.setBounds(190, 270, 37, 16);

        jl_R$2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$2.setText("R$");
        getContentPane().add(jl_R$2);
        jl_R$2.setBounds(200, 310, 17, 20);

        jl_R$3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$3.setText("R$");
        getContentPane().add(jl_R$3);
        jl_R$3.setBounds(190, 170, 30, 20);

        jl_R$4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$4.setText("R$");
        getContentPane().add(jl_R$4);
        jl_R$4.setBounds(190, 450, 17, 20);

        jcb_queijo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_queijo.setForeground(new java.awt.Color(255, 255, 255));
        jcb_queijo.setText("Queijo.......................................");
        getContentPane().add(jcb_queijo);
        jcb_queijo.setBounds(250, 180, 190, 24);

        jcb_catupiry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_catupiry.setForeground(new java.awt.Color(255, 255, 255));
        jcb_catupiry.setText("Catupiry.......................................");
        getContentPane().add(jcb_catupiry);
        jcb_catupiry.setBounds(250, 230, 180, 24);

        jcb_cheddar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_cheddar.setForeground(new java.awt.Color(255, 255, 255));
        jcb_cheddar.setText("Cheddar........................................");
        getContentPane().add(jcb_cheddar);
        jcb_cheddar.setBounds(250, 270, 180, 24);

        jcb_barbecue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_barbecue.setForeground(new java.awt.Color(255, 255, 255));
        jcb_barbecue.setText("Barbecue................................");
        getContentPane().add(jcb_barbecue);
        jcb_barbecue.setBounds(250, 320, 180, 24);

        jl_bebidas.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        jl_bebidas.setForeground(new java.awt.Color(255, 255, 255));
        jl_bebidas.setText("BEBIDAS");
        getContentPane().add(jl_bebidas);
        jl_bebidas.setBounds(60, 380, 120, 20);

        jl_R$5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$5.setText("R$");
        getContentPane().add(jl_R$5);
        jl_R$5.setBounds(190, 400, 17, 20);

        jl_R$6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$6.setText("R$");
        getContentPane().add(jl_R$6);
        jl_R$6.setBounds(190, 500, 17, 20);

        jl_R$7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$7.setText("R$");
        getContentPane().add(jl_R$7);
        jl_R$7.setBounds(190, 220, 17, 20);

        jl_R$8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$8.setText("R$");
        getContentPane().add(jl_R$8);
        jl_R$8.setBounds(440, 220, 20, 20);

        jl_R$9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$9.setText("R$");
        getContentPane().add(jl_R$9);
        jl_R$9.setBounds(440, 310, 17, 20);

        jl_R$10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$10.setText("R$");
        getContentPane().add(jl_R$10);
        jl_R$10.setBounds(440, 170, 30, 20);

        jl_R$11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_R$11.setText("R$");
        getContentPane().add(jl_R$11);
        jl_R$11.setBounds(440, 270, 37, 20);

        jl_precoqueijo.setText("1,50");
        getContentPane().add(jl_precoqueijo);
        jl_precoqueijo.setBounds(440, 190, 40, 20);

        jl_precocatupiry.setText("2,00");
        getContentPane().add(jl_precocatupiry);
        jl_precocatupiry.setBounds(440, 330, 30, 20);

        jl_precocheddar.setText("2,50");
        getContentPane().add(jl_precocheddar);
        jl_precocheddar.setBounds(440, 280, 30, 30);

        jl_precobarbecue.setText("2,00");
        getContentPane().add(jl_precobarbecue);
        jl_precobarbecue.setBounds(440, 240, 30, 20);

        jl_precoagua.setText("4,00");
        getContentPane().add(jl_precoagua);
        jl_precoagua.setBounds(190, 420, 50, 16);

        jl_precorefrigerante.setText("6,00");
        getContentPane().add(jl_precorefrigerante);
        jl_precorefrigerante.setBounds(190, 470, 30, 16);

        jl_precocerveja.setText("7,00");
        getContentPane().add(jl_precocerveja);
        jl_precocerveja.setBounds(190, 520, 40, 16);

        jrb_agua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_agua.setForeground(new java.awt.Color(255, 255, 255));
        jrb_agua.setText("Água...................................");
        jrb_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_aguaActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_agua);
        jrb_agua.setBounds(20, 410, 170, 24);

        jrb_refri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_refri.setForeground(new java.awt.Color(255, 255, 255));
        jrb_refri.setText("Refrigerante.............................");
        jrb_refri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_refriActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_refri);
        jrb_refri.setBounds(20, 460, 170, 24);

        jrb_cerveja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_cerveja.setForeground(new java.awt.Color(255, 255, 255));
        jrb_cerveja.setText("Cerveja....................................");
        jrb_cerveja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_cervejaActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_cerveja);
        jrb_cerveja.setBounds(20, 500, 170, 24);

        jb_calcular.setBackground(new java.awt.Color(255, 255, 51));
        jb_calcular.setText("calcular");
        jb_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(jb_calcular);
        jb_calcular.setBounds(250, 380, 90, 22);

        jb_resetar.setBackground(new java.awt.Color(255, 255, 51));
        jb_resetar.setText("resetar");
        jb_resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resetarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_resetar);
        jb_resetar.setBounds(250, 420, 90, 20);

        jl_subtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_subtotal.setForeground(new java.awt.Color(255, 255, 255));
        jl_subtotal.setText("subtotal");
        getContentPane().add(jl_subtotal);
        jl_subtotal.setBounds(380, 350, 100, 30);

        jl_total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_total.setForeground(new java.awt.Color(255, 255, 255));
        jl_total.setText("total");
        getContentPane().add(jl_total);
        jl_total.setBounds(390, 450, 37, 16);

        jl_totaladicionais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_totaladicionais.setForeground(new java.awt.Color(255, 255, 255));
        jl_totaladicionais.setText("adicionais");
        getContentPane().add(jl_totaladicionais);
        jl_totaladicionais.setBounds(370, 400, 70, 20);

        jl_entregarapida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_entregarapida.setForeground(new java.awt.Color(255, 255, 255));
        jl_entregarapida.setText("Entrega Full");
        getContentPane().add(jl_entregarapida);
        jl_entregarapida.setBounds(30, 560, 80, 20);

        jl_whats.setForeground(new java.awt.Color(255, 255, 255));
        jl_whats.setText("Eduarda Smaniotto");
        getContentPane().add(jl_whats);
        jl_whats.setBounds(150, 550, 110, 16);

        jtf_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_subtotal);
        jtf_subtotal.setBounds(370, 380, 71, 22);

        jtf_adicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_adicionaisActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_adicionais);
        jtf_adicionais.setBounds(370, 430, 71, 22);

        jtf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_totalActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_total);
        jtf_total.setBounds(370, 470, 71, 22);

        jl_dinheiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_dinheiro.setForeground(new java.awt.Color(255, 255, 255));
        jl_dinheiro.setText("Informe quanto você pagará");
        getContentPane().add(jl_dinheiro);
        jl_dinheiro.setBounds(350, 660, 180, 40);

        jl_nome.setForeground(new java.awt.Color(255, 255, 255));
        jl_nome.setText("Nome");
        getContentPane().add(jl_nome);
        jl_nome.setBounds(240, 450, 37, 16);
        getContentPane().add(jtf_nome);
        jtf_nome.setBounds(290, 450, 71, 22);

        jl_rua.setForeground(new java.awt.Color(255, 255, 255));
        jl_rua.setText("Rua");
        getContentPane().add(jl_rua);
        jl_rua.setBounds(240, 480, 20, 16);

        btn_gerarpedido.setText("gerar pedido");
        btn_gerarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarpedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gerarpedido);
        btn_gerarpedido.setBounds(380, 510, 110, 22);
        getContentPane().add(jtf_rua);
        jtf_rua.setBounds(290, 480, 71, 22);

        jl_numero.setForeground(new java.awt.Color(255, 255, 255));
        jl_numero.setText("Numero");
        getContentPane().add(jl_numero);
        jl_numero.setBounds(240, 510, 44, 16);
        getContentPane().add(jtf_numero);
        jtf_numero.setBounds(290, 510, 64, 22);
        getContentPane().add(jtf_bairro);
        jtf_bairro.setBounds(290, 540, 64, 22);

        jl_bairro.setForeground(new java.awt.Color(255, 255, 255));
        jl_bairro.setText("Bairro");
        getContentPane().add(jl_bairro);
        jl_bairro.setBounds(240, 540, 37, 16);
        getContentPane().add(jtf_cep);
        jtf_cep.setBounds(290, 570, 64, 22);

        jl_cep.setForeground(new java.awt.Color(255, 255, 255));
        jl_cep.setText("CEP");
        getContentPane().add(jl_cep);
        jl_cep.setBounds(240, 570, 21, 16);
        getContentPane().add(jtf_celular);
        jtf_celular.setBounds(430, 550, 64, 22);

        jl_celular.setText("celular");
        getContentPane().add(jl_celular);
        jl_celular.setBounds(380, 550, 35, 16);

        jb_fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CEIA_____\\Desktop\\novo.png")); // NOI18N
        jb_fundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_fundoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_fundo);
        jb_fundo.setBounds(-30, -90, 600, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_burguerbaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_burguerbaconActionPerformed
        if(jrb_burguerbacon.isSelected()){
            jrb_burguerduplo.setSelected(false);
            jrb_burguerfrango.setSelected(false);
            jrb_modadacasa.setSelected(false);
        }
    }//GEN-LAST:event_jrb_burguerbaconActionPerformed

    private void jrb_burguerfrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_burguerfrangoActionPerformed
        if(jrb_burguerfrango.isSelected()){
            jrb_burguerbacon.setSelected(false);
            jrb_modadacasa.setSelected(false);
            jrb_burguerduplo.setSelected(false);
        }
    }//GEN-LAST:event_jrb_burguerfrangoActionPerformed

    private void jrb_modadacasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_modadacasaActionPerformed
        if(jrb_modadacasa.isSelected()){
            jrb_burguerbacon.setSelected(false);
            jrb_burguerfrango.setSelected(false);
            jrb_burguerduplo.setSelected(false);
        }
    }//GEN-LAST:event_jrb_modadacasaActionPerformed

    private void jrb_burguerduploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_burguerduploActionPerformed
        if(jrb_burguerduplo.isSelected()){
            jrb_burguerbacon.setSelected(false);
            jrb_modadacasa.setSelected(false);
            jrb_burguerfrango.setSelected(false);
        }
    }//GEN-LAST:event_jrb_burguerduploActionPerformed

    private void jrb_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_aguaActionPerformed
        if(jrb_agua.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_refri.setSelected(false);
        }
    }//GEN-LAST:event_jrb_aguaActionPerformed

    private void jrb_refriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_refriActionPerformed
        if(jrb_refri.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_agua.setSelected(false);
        }
    }//GEN-LAST:event_jrb_refriActionPerformed

    private void jrb_cervejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_cervejaActionPerformed
        if(jrb_cerveja.isSelected()){
            jrb_agua.setSelected(false);
            jrb_refri.setSelected(false);
        }
    }//GEN-LAST:event_jrb_cervejaActionPerformed

    private void jb_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_calcularActionPerformed
        double total=0, subtotal=0, troco, adicionais=0, dinheiro;
        
        //burguers
        if(jrb_burguerbacon.isSelected()){
            subtotal = subtotal + 21.90;
        }
        else if(jrb_burguerduplo.isSelected()){
            subtotal = subtotal + 24.90;
        }
        else if(jrb_burguerfrango.isSelected()){
            subtotal = subtotal + 18.90;
        }
        else if(jrb_modadacasa.isSelected()){
            subtotal = subtotal + 21.90;
        }
        //bebidas
        if(jrb_agua.isSelected()){
            subtotal = subtotal + 4.00;
        }
        else if(jrb_cerveja.isSelected()){
            subtotal = subtotal + 7.00;
        }
        else if(jrb_refri.isSelected()){
            subtotal = subtotal + 6.00;
        }
     
        //adicionais
        if(jcb_barbecue.isSelected()){
            adicionais = adicionais + 2.00;
        }
        if(jcb_catupiry.isSelected()){
            adicionais = adicionais + 2.00;
        }
        if(jcb_queijo.isSelected()){
            adicionais = adicionais + 1.50;
        }
        if(jcb_cheddar.isSelected()){
            adicionais = adicionais + 2.50;
        }
        total = subtotal + adicionais;
        
        //dinheiro = Double.parseDouble(jtf_digitedinheiro.getText());
        //troco = dinheiro - total;
        //jtf_troco.setText(Double.toString(troco));
        
        //totais
        jtf_adicionais.setText(Double.toString(adicionais));
        jtf_subtotal.setText(Double.toString(subtotal));
        jtf_total.setText(Double.toString(total));
        
    }//GEN-LAST:event_jb_calcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_fundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_fundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_fundoActionPerformed

    private void jtf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_totalActionPerformed

    private void jtf_adicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_adicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_adicionaisActionPerformed

    private void jtf_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_subtotalActionPerformed

    private void jb_resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resetarActionPerformed
        jrb_burguerbacon.setSelected(false);
        jrb_burguerduplo.setSelected(false);
        jrb_burguerfrango.setSelected(false);
        jrb_modadacasa.setSelected(false);
        jcb_barbecue.setSelected(false);
        jcb_catupiry.setSelected(false);
        jcb_cheddar.setSelected(false);
        jcb_queijo.setSelected(false);
        jcb_catupiry.setSelected(false);
        jrb_agua.setSelected(false);
        jrb_cerveja.setSelected(false);
        jrb_refri.setSelected(false);
    }//GEN-LAST:event_jb_resetarActionPerformed

    private void btn_gerarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarpedidoActionPerformed
        String entrega = "Dados da Entrega:"+"Nome do Cliente: "+jtf_nome.getText()+"\n Rua: "+ jtf_rua.getText()+" \n Numero: "+jtf_numero.getText()
                +" \n Bairro: "+jtf_bairro.getText()+"\n CEP: "+jtf_cep.getText()+"\n celular"+jtf_celular.getText();
        
        
        byte[] buff = entrega.getBytes();
        
        
        
        try{
            r++;
            RandomAccessFile raf = new RandomAccessFile("C:\\testeJava\\pedido"+jtf_nome.getText()+".txt", "rw");
            raf.write(buff);
        }
        catch(IOException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_gerarpedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gerarpedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jb_calcular;
    private javax.swing.JButton jb_fundo;
    private javax.swing.JButton jb_resetar;
    private javax.swing.JCheckBox jcb_barbecue;
    private javax.swing.JCheckBox jcb_catupiry;
    private javax.swing.JCheckBox jcb_cheddar;
    private javax.swing.JCheckBox jcb_queijo;
    private javax.swing.JLabel jl_R$;
    private javax.swing.JLabel jl_R$10;
    private javax.swing.JLabel jl_R$11;
    private javax.swing.JLabel jl_R$2;
    private javax.swing.JLabel jl_R$3;
    private javax.swing.JLabel jl_R$4;
    private javax.swing.JLabel jl_R$5;
    private javax.swing.JLabel jl_R$6;
    private javax.swing.JLabel jl_R$7;
    private javax.swing.JLabel jl_R$8;
    private javax.swing.JLabel jl_R$9;
    private javax.swing.JLabel jl_adicionais;
    private javax.swing.JLabel jl_bairro;
    private javax.swing.JLabel jl_bebidas;
    private javax.swing.JLabel jl_burguers;
    private javax.swing.JLabel jl_celular;
    private javax.swing.JLabel jl_cep;
    private javax.swing.JLabel jl_dinheiro;
    private javax.swing.JLabel jl_entregarapida;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JLabel jl_numero;
    private javax.swing.JLabel jl_precoagua;
    private javax.swing.JLabel jl_precobarbecue;
    private javax.swing.JLabel jl_precoburguerbacon;
    private javax.swing.JLabel jl_precoburguerduplo;
    private javax.swing.JLabel jl_precoburguerfrango;
    private javax.swing.JLabel jl_precoburguermodadacasa;
    private javax.swing.JLabel jl_precocatupiry;
    private javax.swing.JLabel jl_precocerveja;
    private javax.swing.JLabel jl_precocheddar;
    private javax.swing.JLabel jl_precoqueijo;
    private javax.swing.JLabel jl_precorefrigerante;
    private javax.swing.JLabel jl_rua;
    private javax.swing.JLabel jl_subtotal;
    private javax.swing.JLabel jl_toleburguer;
    private javax.swing.JLabel jl_total;
    private javax.swing.JLabel jl_totaladicionais;
    private javax.swing.JLabel jl_whats;
    private javax.swing.JRadioButton jrb_agua;
    private javax.swing.JRadioButton jrb_burguerbacon;
    private javax.swing.JRadioButton jrb_burguerduplo;
    private javax.swing.JRadioButton jrb_burguerfrango;
    private javax.swing.JRadioButton jrb_cerveja;
    private javax.swing.JRadioButton jrb_modadacasa;
    private javax.swing.JRadioButton jrb_refri;
    private javax.swing.JTextField jtf_adicionais;
    private javax.swing.JTextField jtf_bairro;
    private javax.swing.JTextField jtf_celular;
    private javax.swing.JTextField jtf_cep;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_numero;
    private javax.swing.JTextField jtf_rua;
    private javax.swing.JTextField jtf_subtotal;
    private javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
